version: '{build}'
os: Visual Studio 2017
cache: C:\Users\appveyor\.nuget\packages
build_script:
- ps: >-
    dotnet restore

    dotnet build --configuration Release /p:BuildNumber=$env:APPVEYOR_BUILD_NUMBER