version: '{build}'
os: Visual Studio 2017
cache: C:\Users\appveyor\.nuget\packages
build_script:
  - dotnet restore
  - dotnet build --configuration Release /p:BuildNumber=%APPVEYOR_BUILD_NUMBER%
  - dotnet pack -c Release -o packages --no-build /p:BuildNumber=%APPVEYOR_BUILD_NUMBER%

test_script:
  - dotnet test test/typify.Tests/typify.Tests.csproj