version: '{build}'
os: Visual Studio 2017 RC
cache: C:\Users\appveyor\.dnx\packages
build_script:
- ps: >-
    dotnet restore src\Typify

    dotnet build src\Typify --configuration Release

    dotnet restore src\Typify.Cli

    dotnet build src\Typify.Cli --configuration Release
