version: '{build}'
os: Visual Studio 2017 RC
cache: C:\Users\appveyor\.dnx\packages
build_script:
- ps: >-
    dotnet restore src\Typify.NET\Typify.NET.csproj

    dotnet restore src\typify.cli\typify.csproj

    dotnet build --configuration Release
